EQUIPOS = {
    "Atlas FC": "atlas",
    "Atlético San Luis": "atletico_de_san_luis",
    "CD Guadalajara": "cd_guadalajara",
    "CD Toluca": "toluca",
    "CF Monterrey": "monterrey",
    "CF Pachuca": "pachuca",
    "Club América": "club_america",
    "Club León": "club_leon",
    "Club Necaxa": "necaxa",
    "Club Puebla": "puebla",
    "Club Tijuana": "club_tijuana",
    "Cruz Azul": "cruz_azul",
    "FC Juárez": "fc_juarez",
    "Mazatlán FC": "mazatlan_fc",
    "Pumas UNAM": "unam_pumas",
    "Querétaro FC": "queretaro_fc",
    "Santos Laguna": "santos_laguna",
    "Tigres UANL": "tigres_uanl"
}
